/*
 * parsing table for parser
 * DO NOT edit this file, this file is generated by lalr parser generator
 *
 * Copyright (C) 2022 Ligang Wang <ligangwangs@gmail.com>
 *
 */
#define M_PARSING_INITIALIZER 1
#include "parser/m_parsing_table.h"

const struct parse_rule m_parsing_rules[PARSING_RULE_COUNT] = {
    /*rule 0*/ { 0, { 0, 0, 0, 0, 0, 0, 0 }, 0, { 0, { 0, 0, 0, 0, 0 }, 0 } }
};

const struct parser_action m_parsing_table[PARSING_STATE_COUNT][PARSING_SYMBOL_COUNT] = {
    /*row 0*/ { ACTION_ERROR, 0 }
};
