/*
 * parsing table for parser
 * DO NOT edit this file, this file is generated by pgen
 * 
 * Copyright (C) 2022 Ligang Wang <ligangwangs@gmail.com>
 *     
 */    
#define PARSING_RULE_COUNT 142
#define PARSING_STATE_COUNT 10
#define PARSING_SYMBOL_COUNT 196
