name: CMake WASM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Install LLVM & LLD
      run: |
        sudo apt remove llvm-10
        sudo apt remove llvm-11
        sudo apt remove llvm-12
        sudo apt remove clang-11
        sudo apt autoclean && sudo apt autoremove
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main"
        sudo apt-get install llvm-13 lld-13 clang-13
        sudo ln /usr/bin/llvm-config-13 /usr/bin/llvm-config
        sudo ln /usr/bin/llvm-ar-13 /usr/bin/llvm-ar
        sudo ln /usr/bin/llvm-nm-13 /usr/bin/llvm-nm
        sudo ln /usr/bin/llvm-ranlib-13 /usr/bin/llvm-ranlib
        sudo ln -f /usr/bin/clang-13 /usr/bin/clang
        sudo ln -f /usr/bin/clang++-13 /usr/bin/clang++
        sudo ln -f /usr/bin/wasm-ld-13 /usr/bin/wasm-ld
        
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Get wasmtime
      run: |
        curl https://wasmtime.dev/install.sh -sSf | bash
        echo "${HOME}/.wasmtime/bin" >> $GITHUB_PATH

    - name: Test wasmtime path
      run: |
        wasmtime -V

    - name: Build wasi-libc
      run: (cd ${{github.workspace}}/extern/wasi-libc && make)
    - name: download libclang_rt.builtins-wasm32-wasi
      run: | 
        wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-14/libclang_rt.builtins-wasm32-wasi-14.0.tar.gz
        sudo tar xzvf libclang_rt.builtins-wasm32-wasi-14.0.tar.gz
        rm -r -f libclang_rt.builtins-wasm32-wasi-14.0.tar.gz
        
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWASM=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Build m
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

    #use nodes now
    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: cd ${{github.workspace}}/test
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test