name: Jekyll Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.1.0
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
